In [99]:
%timeit [ i for i in range (1,10)]

306 ns ± 2.19 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [95]:
import numpy as np
%timeit np.arange(1,50)*4

1.66 μs ± 182 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [85]:
%timeit [i*4 for i in range (1,10)]

422 ns ± 26.6 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [115]:
a=np.array([1,'2',34,5,])
print(type(a))
a

<class 'numpy.ndarray'>


array(['1', '2', '34', '5'], dtype='<U11')

In [119]:
l=[1,2,3,4,]
print(type(l))
l


<class 'list'>


[1, 2, 3, 4]

In [157]:
lst=[]
for l in range(1,5):
    aa=int(input('enter no:'))
    lst.append(aa)
    
print(np.array(lst))

enter no: 7
enter no: 6
enter no: 6
enter no: 6


[7 6 6 6]


In [175]:
a=np.array([1,2,34,4])
a

array([ 1,  2, 34,  4])

In [431]:
a=np.array([[1,2,3,41,2,3]],ndmin=10)
a

array([[[[[[[[[[ 1,  2,  3, 41,  2,  3]]]]]]]]]])

In [433]:
a = np.array([1, 2, 3, 41, 2, 3])
a.ndim

1

In [159]:
# zeroes and ones

In [337]:
ar=np.zeros((4,6))
ar

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [335]:
a=np.zeros([3,4,5])
print(a.ndim)

3


In [315]:
a=np.ones([4,6])
a

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [243]:
a=np.empty(4)
a

array([1., 1., 1., 1.])

In [323]:
a=np.arange((5))
a

array([0, 1, 2, 3, 4])

In [343]:
a=np.eye(7,7)
a

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [359]:
np.linspace(1,5,num=88)

array([1.        , 1.04597701, 1.09195402, 1.13793103, 1.18390805,
       1.22988506, 1.27586207, 1.32183908, 1.36781609, 1.4137931 ,
       1.45977011, 1.50574713, 1.55172414, 1.59770115, 1.64367816,
       1.68965517, 1.73563218, 1.7816092 , 1.82758621, 1.87356322,
       1.91954023, 1.96551724, 2.01149425, 2.05747126, 2.10344828,
       2.14942529, 2.1954023 , 2.24137931, 2.28735632, 2.33333333,
       2.37931034, 2.42528736, 2.47126437, 2.51724138, 2.56321839,
       2.6091954 , 2.65517241, 2.70114943, 2.74712644, 2.79310345,
       2.83908046, 2.88505747, 2.93103448, 2.97701149, 3.02298851,
       3.06896552, 3.11494253, 3.16091954, 3.20689655, 3.25287356,
       3.29885057, 3.34482759, 3.3908046 , 3.43678161, 3.48275862,
       3.52873563, 3.57471264, 3.62068966, 3.66666667, 3.71264368,
       3.75862069, 3.8045977 , 3.85057471, 3.89655172, 3.94252874,
       3.98850575, 4.03448276, 4.08045977, 4.12643678, 4.17241379,
       4.2183908 , 4.26436782, 4.31034483, 4.35632184, 4.40229

In [451]:
a=np.random.ranf((2,8,3))
a.ndim
a

array([[[0.6093129 , 0.07428497, 0.76031941],
        [0.92842485, 0.03178504, 0.79990806],
        [0.52002072, 0.86993409, 0.54083709],
        [0.19506253, 0.28816327, 0.34009688],
        [0.76537141, 0.40514433, 0.71369002],
        [0.17077923, 0.07859404, 0.79686585],
        [0.54138492, 0.25114907, 0.60985366],
        [0.78742112, 0.96070223, 0.15481145]],

       [[0.7969933 , 0.63544712, 0.64101444],
        [0.58781279, 0.36766786, 0.50560803],
        [0.44150008, 0.911475  , 0.63070949],
        [0.5227858 , 0.85647652, 0.94538516],
        [0.9988451 , 0.41051986, 0.71490354],
        [0.54746683, 0.62341359, 0.70449893],
        [0.84567568, 0.73266812, 0.824424  ],
        [0.26153717, 0.13512837, 0.10694187]]])

In [470]:
np.random.randint(5,10,6)

array([9, 5, 8, 8, 8, 5])

In [480]:
b=np.float32(a)
b

array([[[0.6093129 , 0.07428497, 0.7603194 ],
        [0.92842484, 0.03178504, 0.79990804],
        [0.5200207 , 0.8699341 , 0.5408371 ],
        [0.19506253, 0.28816327, 0.34009686],
        [0.76537144, 0.40514433, 0.71369004],
        [0.17077923, 0.07859404, 0.7968658 ],
        [0.54138494, 0.2511491 , 0.6098537 ],
        [0.7874211 , 0.96070224, 0.15481146]],

       [[0.7969933 , 0.63544714, 0.64101446],
        [0.5878128 , 0.36766785, 0.505608  ],
        [0.44150007, 0.911475  , 0.63070947],
        [0.5227858 , 0.85647655, 0.94538516],
        [0.9988451 , 0.41051987, 0.71490353],
        [0.5474668 , 0.62341356, 0.70449895],
        [0.8456757 , 0.7326681 , 0.824424  ],
        [0.26153716, 0.13512838, 0.10694187]]], dtype=float32)

In [506]:
x=np.array([1,2,3,4,],dtype="f")
x
a=np.int_(x)
a.dtype

dtype('int32')

In [669]:
a=np.array([1,2,3,4,5,6,4,5,3,4,5,6])
print(a.shape)
x=a.reshape(3,2,2)
x


(12,)


3

In [577]:
np.add([5 ,3], 5)

array([10,  8])

In [587]:
np.subtract(a, 4)


array([-3, -2, -1,  0,  1,  2,  0,  1, -1,  0,  1,  2])

In [603]:
np.argmax(a)

5

In [613]:
b

array([[[0.6093129 , 0.07428497, 0.7603194 ],
        [0.92842484, 0.03178504, 0.79990804],
        [0.5200207 , 0.8699341 , 0.5408371 ],
        [0.19506253, 0.28816327, 0.34009686],
        [0.76537144, 0.40514433, 0.71369004],
        [0.17077923, 0.07859404, 0.7968658 ],
        [0.54138494, 0.2511491 , 0.6098537 ],
        [0.7874211 , 0.96070224, 0.15481146]],

       [[0.7969933 , 0.63544714, 0.64101446],
        [0.5878128 , 0.36766785, 0.505608  ],
        [0.44150007, 0.911475  , 0.63070947],
        [0.5227858 , 0.85647655, 0.94538516],
        [0.9988451 , 0.41051987, 0.71490353],
        [0.5474668 , 0.62341356, 0.70449895],
        [0.8456757 , 0.7326681 , 0.824424  ],
        [0.26153716, 0.13512838, 0.10694187]]], dtype=float32)

In [619]:
np.max(b,axis=1)

array([[0.92842484, 0.96070224, 0.79990804],
       [0.9988451 , 0.911475  , 0.94538516]], dtype=float32)

In [621]:
np.cumsum(a)

array([ 1,  3,  6, 10, 15, 21, 25, 30, 33, 37, 42, 48])

In [653]:
var=np.array([[1,2,3],[1,8,3],[2,3,4]])
var2=np.array([[1],[2],[3]])
print(var)
print()
print(var.shape)
print()
print(var2)
print(var2.shape)
a=var+var2
a.shape


[[1 2 3]
 [1 8 3]
 [2 3 4]]

(3, 3)

[[1]
 [2]
 [3]]
(3, 1)


(3, 3)

In [701]:
var[-1,1:]

array([3, 4])

In [699]:
a[::4]


array([1, 5, 3])

In [729]:
a=np.array([[1,2,3],[4,8,5]])
for l in a:
    for i in l:
        print(i)

1
2
3
4
8
5


In [735]:
np.array_split(a,3,axis=1)

[array([[1],
        [4]]),
 array([[2],
        [8]]),
 array([[3],
        [5]])]